export const clientList = [
  'JCgontinho',
  'MRV',
  'Paulootavio',
  'Odebrecht',
  'Cirela',
  'Construtora Vitale',
  'Construtora Craft',
  'Construtora Mjre',
  'Otavio Mesquita',
  'Octavio',
  'Otorrino',
  'Oliver',
  'Omar',
  'Oswald',
  'Osvaldo',
  'Olivia',
  'Otavio Oliveira',
  'Otavio Flavio',
  'Otavio Rodrigues',
  'Otavio Ribeiro',
];
export const storeList = [
  'Leroy Merlim',
  'Castelo Forte',
  'Amanco',
  'Tigre',
  'Krona',
  'Ferroplast',
  'Voturan',
  'Deca',
  'lorenzetti',
  'Bafran',
];
